### ISSUE TITLE
[Question] Can encryption with Chunky2048 be made in blocks or is it seekable?

### ISSUE THREAD

**Issue by phantomcraft** [rmlibre/aiootp#2]
When encrypting using Chunky2048, is it possible to do it in small blocks as any regular block cipher?

Or is at least have a seekable keystream?

**Comment by rmlibre** [comment]
Hi there,

No, I would not recommend trying to make Chunky2048 into a seekable cipher, if by seekable you mean jumping ahead in the key stream to some known future position (like to jump to minute 45 of a movie, or something like that.) Nor do I think it would be possible. The smallest blocksize for Chunky2048 is 256-bytes, 2048-bits, which is where the name comes from. The large and constant size is intended as a security feature, to automate the masking of the sizes of plaintexts which should reduce the amount of information that can be gleaned from observing ciphertexts.

To explain further why Chunky2048 isn't seekable: In the tradeoff decision between providing seekability and providing better salt reuse-misuse resistance (let's call it SRMR for short), better SRMR was chosen. In specific, the ciphertext is continuously fed, block by block, into a sha3_256 hashing object for authentication. And, the output of that updated hashing object is also continuously fed back into the hashing objects used to create the encryption key stream. This ensures that, even if the salt is the same (and for some reason so is the SIV, probably to do with misuse of the cipher) for two distinct encrypted plaintext messages, that the key stream will still be unique for each message. This is the best that could be done to improve SRMR if the worst case scenario happens and both the salt and SIV are the same for two messages. However, it's limited in effectiveness, because the key stream will only begin to produce unique outputs after the block where the first difference in the plaintexts occurs.

This also means that the cipher is inherently consecutive, and it cannot be seekable, since each block is tied to the next and must be processed for the cipher to function properly.

**Comment by phantomcraft** [comment]
I got. I asked that because I was seeking for a seekable cipher for my future projects.

**Comment by rmlibre** [comment]
No problem.

Although the cipher itself isn't seekable, there is an easy and secure way to use Chunky2048 to gain seekability -- that would be to create a communication protocol. You'd divide the plaintext into known chunk sizes, use the 24-byte salt as an ordered pseudo-random chunk ID, and encrypt each chunk separately.

You can seek to a particular chunk by searching for its ID / salt amongst the set of encrypted chunks. And you can size the chunks as appropriate for the granularity of seekability you're looking for. 

This does, however, come with a size overhead in ciphertexts, since each chunk would have its own HMAC, salt, SIV, inner-header prepended to the plaintext, and padding appended to the plaintext.

The size efficiency can be improved with larger chunk sizes, and the appended plaintext padding can be avoided by sizing the plaintext chunks in exact increments of 232 + n * 256 bytes.

**Comment by phantomcraft** [comment]
/\ Interesting.
